

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class lupapass extends javax.swing.JFrame {

    public static String query = "";
    public static Statement st;
    public static ResultSet r;

    /**
     * Creates new form lupapass
     */
    public lupapass() {
        initComponents();
        loadData();
    }

    public void loadData() {

        try {
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String Query = "select * from admin";
            ResultSet r = s.executeQuery(Query);
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    public void cari() {
        try {
            String cari = tid.getText();
            String cari2 = tmail.getText();
            Connection c = koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "select password from admin where username like '" + cari + "' and email like '" + cari2 + "'";
            ResultSet rs = s.executeQuery(sql);
            if (rs.next()) {
                ttampl.setText("Password = " + rs.getString(1));
            } else {
                JOptionPane.showMessageDialog(null, "Username & Email Tidak Benar!!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                tid.requestFocusInWindow();
                tid.setText("");
                tmail.setText("");
            }
            //s.close();
            //c.close();
        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bkembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bcari = new javax.swing.JButton();
        ttampl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 40));
        jPanel1.setLayout(null);

        bkembali.setBackground(new java.awt.Color(204, 204, 255));
        bkembali.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        bkembali.setText("X");
        bkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkembaliActionPerformed(evt);
            }
        });
        jPanel1.add(bkembali);
        bkembali.setBounds(310, 0, 53, 40);

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 400));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forget Password?");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(40, 10, 280, 50);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(140, 100, 100, 30);

        tid.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setPreferredSize(new java.awt.Dimension(14, 26));
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel3.add(tid);
        tid.setBounds(80, 140, 210, 30);

        tmail.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        tmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tmail.setPreferredSize(new java.awt.Dimension(14, 26));
        tmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmailActionPerformed(evt);
            }
        });
        jPanel3.add(tmail);
        tmail.setBounds(80, 220, 210, 30);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(160, 190, 50, 20);

        bcari.setBackground(new java.awt.Color(204, 204, 255));
        bcari.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        bcari.setText("Find");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel3.add(bcari);
        bcari.setBounds(180, 270, 110, 40);

        ttampl.setBackground(new java.awt.Color(255, 204, 255));
        ttampl.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        ttampl.setForeground(java.awt.Color.red);
        ttampl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ttampl.setBorder(null);
        ttampl.setCaretColor(new java.awt.Color(204, 204, 255));
        ttampl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttamplActionPerformed(evt);
            }
        });
        jPanel3.add(ttampl);
        ttampl.setBounds(30, 340, 300, 60);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel4.setText("don't worry and stay put your username and e-mail :)");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 50, 270, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(376, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        cari();
    }//GEN-LAST:event_bcariActionPerformed

    private void bkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkembaliActionPerformed
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_bkembaliActionPerformed

private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_tidActionPerformed

    private void tmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmailActionPerformed

    private void ttamplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttamplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttamplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lupapass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new lupapass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tmail;
    private javax.swing.JTextField ttampl;
    // End of variables declaration//GEN-END:variables
}

//bug: jika username memiliki kesamaan, makan yang digunakan adalah id yang paling atas